name: Decode Vertex Key

on:
  workflow_dispatch:
  push:
    branches: [master] # or your default branch

jobs:
  decode-key:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Decode vertex-key.json from secret
        run: |
          echo ${{ secrets.VERTEX_KEY_B64 }} | base64 --decode > vertex-key.json
